import collections

REFERENCE = "snes9x 1.63 apu/bapu/smp/debugger/disassembler.cpp"
REFERENCE_SHA256 = "7f3b5693f40d2ed888870f655f2adef2d7838ffb4527772fb6a4c6b8b937ba80"

Instruction = collections.namedtuple("Instruction", "address size text opcode")

OPCODES = (
    ("nop", 1),
    ("tcall 0", 1),
    ("set0 ${dp0}", 2),
    ("bbs0 ${dp0},${rel3}", 3),
    ("or a,${dp0}", 2),
    ("or a,${abs}", 3),
    ("or a,(x)", 1),
    ("or a,(${dp0}+x)", 2),
    ("or a,#${op0}", 2),
    ("or ${dp1},${dp0}", 3),
    ("or1 c,${mem}:{bit}", 3),
    ("asl ${dp0}", 2),
    ("asl ${abs}", 3),
    ("push p", 1),
    ("tset ${abs},a", 3),
    ("brk", 1),
    ("bpl ${rel2}", 2),
    ("tcall 1", 1),
    ("clr0 ${dp0}", 2),
    ("bbc0 ${dp0},${rel3}", 3),
    ("or a,${dp0}+x", 2),
    ("or a,${abs}+x", 3),
    ("or a,${abs}+y", 3),
    ("or a,(${dp0})+y", 2),
    ("or ${dp1},#${op0}", 3),
    ("or (x),(y)", 1),
    ("decw ${dp0}", 2),
    ("asl ${dp0}+x", 2),
    ("asl a", 1),
    ("dec x", 1),
    ("cmp x,${abs}", 3),
    ("jmp (${abs}+x)", 3),
    ("clrp", 1),
    ("tcall 2", 1),
    ("set1 ${dp0}", 2),
    ("bbs1 ${dp0},${rel3}", 3),
    ("and a,${dp0}", 2),
    ("and a,${abs}", 3),
    ("and a,(x)", 1),
    ("and a,(${dp0}+x)", 2),
    ("and a,#${op0}", 2),
    ("and ${dp1},${dp0}", 3),
    ("or1 c,!${mem}:{bit}", 3),
    ("rol ${dp0}", 2),
    ("rol ${abs}", 3),
    ("push a", 1),
    ("cbne ${dp0},${rel3}", 3),
    ("bra ${rel2}", 2),
    ("bmi ${rel2}", 2),
    ("tcall 3", 1),
    ("clr1 ${dp0}", 2),
    ("bbc1 ${dp0},${rel3}", 3),
    ("and a,${dp0}+x", 2),
    ("and a,${abs}+x", 3),
    ("and a,${abs}+y", 3),
    ("and a,(${dp0})+y", 2),
    ("and ${dp1},#${op0}", 3),
    ("and (x),(y)", 1),
    ("incw ${dp0}", 2),
    ("rol ${dp0}+x", 2),
    ("rol a", 1),
    ("inc x", 1),
    ("cmp x,${dp0}", 2),
    ("call ${abs}", 3),
    ("setp", 1),
    ("tcall 4", 1),
    ("set2 ${dp0}", 2),
    ("bbs2 ${dp0},${rel3}", 3),
    ("eor a,${dp0}", 2),
    ("eor a,${abs}", 3),
    ("eor a,(x)", 1),
    ("eor a,(${dp0}+x)", 2),
    ("eor a,#${op0}", 2),
    ("eor ${dp1},${dp0}", 3),
    ("and1 c,${mem}:{bit}", 3),
    ("lsr ${dp0}", 2),
    ("lsr ${abs}", 3),
    ("push x", 1),
    ("tclr ${abs},a", 3),
    ("pcall $ff{op0}", 2),
    ("bvc ${rel2}", 2),
    ("tcall 5", 1),
    ("clr2 ${dp0}", 2),
    ("bbc2 ${dp0},${rel3}", 3),
    ("eor a,${dp0}+x", 2),
    ("eor a,${abs}+x", 3),
    ("eor a,${abs}+y", 3),
    ("eor a,(${dp0})+y", 2),
    ("eor ${dp1},#${op0}", 3),
    ("eor (x),(y)", 1),
    ("cmpw ya,${dp0}", 2),
    ("lsr ${dp0}+x", 2),
    ("lsr a", 1),
    ("mov x,a", 1),
    ("cmp y,${abs}", 3),
    ("jmp ${abs}", 3),
    ("clrc", 1),
    ("tcall 6", 1),
    ("set3 ${dp0}", 2),
    ("bbs3 ${dp0},${rel3}", 3),
    ("cmp a,${dp0}", 2),
    ("cmp a,${abs}", 3),
    ("cmp a,(x)", 1),
    ("cmp a,(${dp0}+x)", 2),
    ("cmp a,#${op0}", 2),
    ("cmp ${dp1},${dp0}", 3),
    ("and1 c,!${mem}:{bit}", 3),
    ("ror ${dp0}", 2),
    ("ror ${abs}", 3),
    ("push y", 1),
    ("dbnz ${dp0},${rel3}", 3),
    ("ret", 1),
    ("bvs ${rel2}", 2),
    ("tcall 7", 1),
    ("clr3 ${dp0}", 2),
    ("bbc3 ${dp0},${rel3}", 3),
    ("cmp a,${dp0}+x", 2),
    ("cmp a,${abs}+x", 3),
    ("cmp a,${abs}+y", 3),
    ("cmp a,(${dp0})+y", 2),
    ("cmp ${dp1},#${op0}", 3),
    ("cmp (x),(y)", 1),
    ("addw ya,${dp0}", 2),
    ("ror ${dp0}+x", 2),
    ("ror a", 1),
    ("mov a,x", 1),
    ("cmp y,${dp0}", 2),
    ("reti", 1),
    ("setc", 1),
    ("tcall 8", 1),
    ("set4 ${dp0}", 2),
    ("bbs4 ${dp0},${rel3}", 3),
    ("adc a,${dp0}", 2),
    ("adc a,${abs}", 3),
    ("adc a,(x)", 1),
    ("adc a,(${dp0}+x)", 2),
    ("adc a,#${op0}", 2),
    ("adc ${dp1},${dp0}", 3),
    ("eor1 c,${mem}:{bit}", 3),
    ("dec ${dp0}", 2),
    ("dec ${abs}", 3),
    ("mov y,#${op0}", 2),
    ("pop p", 1),
    ("mov ${dp1},#${op0}", 3),
    ("bcc ${rel2}", 2),
    ("tcall 9", 1),
    ("clr4 ${dp0}", 2),
    ("bbc4 ${dp0},${rel3}", 3),
    ("adc a,${dp0}+x", 2),
    ("adc a,${abs}+x", 3),
    ("adc a,${abs}+y", 3),
    ("adc a,(${dp0})+y", 2),
    ("adc ${dp1},#${op0}", 3),
    ("adc (x),(y)", 1),
    ("subw ya,${dp0}", 2),
    ("dec ${dp0}+x", 2),
    ("dec a", 1),
    ("mov x,sp", 1),
    ("div ya,x", 1),
    ("xcn a", 1),
    ("ei", 1),
    ("tcall 10", 1),
    ("set5 ${dp0}", 2),
    ("bbs5 ${dp0},${rel3}", 3),
    ("sbc a,${dp0}", 2),
    ("sbc a,${abs}", 3),
    ("sbc a,(x)", 1),
    ("sbc a,(${dp0}+x)", 2),
    ("sbc a,#${op0}", 2),
    ("sbc ${dp1},${dp0}", 3),
    ("mov1 c,${mem}:{bit}", 3),
    ("inc ${dp0}", 2),
    ("inc ${abs}", 3),
    ("cmp y,#${op0}", 2),
    ("pop a", 1),
    ("mov (x)+,a", 1),
    ("bcs ${rel2}", 2),
    ("tcall 11", 1),
    ("clr5 ${dp0}", 2),
    ("bbc5 ${dp0},${rel3}", 3),
    ("sbc a,${dp0}+x", 2),
    ("sbc a,${abs}+x", 3),
    ("sbc a,${abs}+y", 3),
    ("sbc a,(${dp0})+y", 2),
    ("sbc ${dp1},#${op0}", 3),
    ("sbc (x),(y)", 1),
    ("movw ya,${dp0}", 2),
    ("inc ${dp0}+x", 2),
    ("inc a", 1),
    ("mov sp,x", 1),
    ("das a", 1),
    ("mov a,(x)+", 1),
    ("di", 1),
    ("tcall 12", 1),
    ("set6 ${dp0}", 2),
    ("bbs6 ${dp0},${rel3}", 3),
    ("mov ${dp0},a", 2),
    ("mov ${abs},a", 3),
    ("mov (x),a", 1),
    ("mov (${dp0}+x),a", 2),
    ("cmp x,#${op0}", 2),
    ("mov ${abs},x", 3),
    ("mov1 ${mem}:{bit},c", 3),
    ("mov ${dp0},y", 2),
    ("mov ${abs},y", 3),
    ("mov x,#${op0}", 2),
    ("pop x", 1),
    ("mul ya", 1),
    ("bne ${rel2}", 2),
    ("tcall 13", 1),
    ("clr6 ${dp0}", 2),
    ("bbc6 ${dp0},${rel3}", 3),
    ("mov ${dp0}+x,a", 2),
    ("mov ${abs}+x,a", 3),
    ("mov ${abs}+y,a", 3),
    ("mov (${dp0})+y,a", 2),
    ("mov ${dp0},x", 2),
    ("mov ${dp0}+y,x", 2),
    ("movw ${dp0},ya", 2),
    ("mov ${dp0}+x,y", 2),
    ("dec y", 1),
    ("mov a,y", 1),
    ("cbne ${dp0}+x,${rel3}", 3),
    ("daa a", 1),
    ("clrv", 1),
    ("tcall 14", 1),
    ("set7 ${dp0}", 2),
    ("bbs7 ${dp0},${rel3}", 3),
    ("mov a,${dp0}", 2),
    ("mov a,${abs}", 3),
    ("mov a,(x)", 1),
    ("mov a,(${dp0}+x)", 2),
    ("mov a,#${op0}", 2),
    ("mov x,${abs}", 3),
    ("not1 c,${mem}:{bit}", 3),
    ("mov y,${dp0}", 2),
    ("mov y,${abs}", 3),
    ("notc", 1),
    ("pop y", 1),
    ("sleep", 1),
    ("beq ${rel2}", 2),
    ("tcall 15", 1),
    ("clr7 ${dp0}", 2),
    ("bbc7 ${dp0},${rel3}", 3),
    ("mov a,${dp0}+x", 2),
    ("mov a,${abs}+x", 3),
    ("mov a,${abs}+y", 3),
    ("mov a,(${dp0})+y", 2),
    ("mov x,${dp0}", 2),
    ("mov x,${dp0}+y", 2),
    ("mov ${dp1},${dp0}", 3),
    ("mov y,${dp0}+x", 2),
    ("inc y", 1),
    ("mov y,a", 1),
    ("dbnz y,${rel2}", 2),
    ("stop", 1),
)


def _signed(value):
    return value - 0x100 if value >= 0x80 else value


def _fields(data, offset, address, p):
    op0 = data[offset + 1] if offset + 1 < len(data) else 0
    op1 = data[offset + 2] if offset + 2 < len(data) else 0
    absolute = op0 | (op1 << 8)
    return {
        "op0": f"{op0:02x}",
        "op1": f"{op1:02x}",
        "dp0": f"{(p << 8) | op0:03x}",
        "dp1": f"{(p << 8) | op1:03x}",
        "abs": f"{absolute:04x}",
        "mem": f"{absolute & 0x1FFF:04x}",
        "bit": f"{absolute >> 13:d}",
        "rel2": f"{(address + 2 + _signed(op0)) & 0xFFFF:04x}",
        "rel3": f"{(address + 3 + _signed(op1)) & 0xFFFF:04x}",
    }


def decode(data, offset, address, p=0):
    if offset >= len(data):
        raise ValueError(f"offset {offset} is past the end of {len(data)} bytes")
    opcode = data[offset]
    template, size = OPCODES[opcode]
    if offset + size > len(data):
        raise ValueError(
            f"opcode {opcode:02X} at {offset} needs {size} bytes, {len(data) - offset} remain"
        )
    text = template.format(**_fields(data, offset, address, p))
    return Instruction(address=address, size=size, text=text, opcode=opcode)


def disassemble(data, offset, address, count=None, p=0):
    produced = 0
    while offset < len(data):
        if count is not None and produced >= count:
            return
        try:
            instruction = decode(data, offset, address, p)
        except ValueError:
            return
        yield instruction
        offset += instruction.size
        address = (address + instruction.size) & 0xFFFF
        produced += 1
