; Street Fighter Alpha 2, S-DD1 bypass.
;
; The S-DD1 decompresses during a DMA when two things are true at once:
;   * $4801 is non-zero, and
;   * the channel's DMAP ($43x0) has bit 3 set, meaning a fixed A-bus address.
; $4801 self-clears after every transfer, so the engine arms it immediately
; before each one. Both facts were taken from the snes9x DMA path
; (dma.cpp, S9xDoDMA, the Settings.SDD1 block), not from documentation.
;
; With no chip fitted, $4800-$4807 are inert, so the arming stores are left in
; place. What has to change is the DMA source, which must point at the
; pre-decompressed copy, and DMAP bit 3, which must be cleared so the address
; increments instead of standing still.
;
; The same shape is used by neviksti's chip-free Star Ocean build, recovered by
; disassembling it at original offset $007000. That build is confirmed working
; on Game Doctor SF7 hardware, which is why this follows it closely.
;
; The USA build of this routine is confirmed working on Game Doctor SF7 and on
; FXPAK Pro hardware. The Japanese build has only ever run under emulation.
;
; Lookup tables, one 64K bank each, generated by sdd1tables.py:
;   $60:xxxx  key       source bank of the stream whose address hashes to xxxx,
;                       or $00 for an empty slot
;   $61:xxxx  dest low
;   $62:xxxx  dest high
;   $63:xxxx  dest bank
; The scan starts at the source address and walks forward until the key matches
; the source bank. sdd1tables.py proves, for all 2815 streams, that this scan
; reaches the right slot and never a wrong one.

!TABLE_KEY   = $600000
!TABLE_LOW   = $610000
!TABLE_HIGH  = $620000
!TABLE_BANK  = $630000

!DMAP        = $004300
!SRC_ADDR    = $004302
!SRC_BANK    = $004304

!FIXED_ADDR  = $08


; ---------------------------------------------------------------------------
; translate(channel)
;
; channel is the DMA register offset: $00 for channel 0, $10 for channel 1,
; $70 for channel 7. Hardcoding it per entry point keeps the register juggling
; out of the hot path; the scan below is already the expensive part.
;
; Entry:  A 8-bit, holding the channel mask the caller is about to store to
;         $420B. X, Y, DBR, DP and every flag are whatever the caller had.
; Exit:   A, X, Y, DBR, DP and all flags restored exactly, so the caller's
;         following "sta $420b" still writes the right mask and any branch on
;         carry still sees the carry it set. M and X widths are restored too.
;
; Clobbers: the DMA channel's $4302-$4304 and bit 3 of its $4300. Nothing else.
; ---------------------------------------------------------------------------
macro translate(channel)
    php                         ; flags out first; $00:885A branches on carry
                                ;   immediately after its "sta $420b"
    phb
    rep #$30                    ; M=0 X=0, 16-bit A and index
    pha
    phx
    phy

    lda.l !SRC_ADDR+<channel>   ; source address the engine just programmed
    tay                         ; Y = scan cursor, starts at the address itself

    sep #$20                    ; M=1, 8-bit A for the key comparison
    lda.l !SRC_BANK+<channel>   ; A = source bank, already OR'd with $40 by the
                                ;   engine, so it reads $C0-$FF

    pea $6060                   ; both bytes are $60, so either pull sets DBR to
    plb                         ;   the key table's bank and the pair leaves the
    plb                         ;   stack balanced
?scan:
    cmp $0000,y                 ; DBR is $60 here, so this reads $60:{Y}.
                                ; Unbounded, exactly as neviksti's is: a miss
                                ; would mean the table is incomplete, and
                                ; sdd1tables.py proves it is not.
    beq ?found
    iny
    bra ?scan

?found:
                                ; DBR stays $60 from here on. Every access below
                                ; is long addressing, which ignores DBR, and the
                                ; caller's DBR comes back off the stack at the
                                ; end. Pulling it here would eat the saved Y.
    phy                         ; keep the slot; Y is restored from this below
    tyx                         ; X = slot, for the long indexed table reads

                                ; Each table is a separate bank, so the three
                                ; destination bytes are three 8-bit reads. A
                                ; 16-bit read of the low table would pick up the
                                ; neighbouring slot, not the high byte.
    lda.l !TABLE_LOW,x
    sta.l !SRC_ADDR+<channel>
    lda.l !TABLE_HIGH,x
    sta.l !SRC_ADDR+1+<channel>
    lda.l !TABLE_BANK,x
    sta.l !SRC_BANK+<channel>

    lda.l !DMAP+<channel>       ; clear the fixed-address bit so the DMA walks
    and #$F7                    ;   forward through the decompressed copy
    sta.l !DMAP+<channel>       ;   instead of re-reading one address

    rep #$30
    ply                         ; discard the saved slot
    ply
    plx
    pla
    plb
    plp                         ; restores M, X and carry together
    rtl
endmacro


; ---------------------------------------------------------------------------
; Entry points. Each hook site JSLs to the one matching its channel.
; ---------------------------------------------------------------------------
org !ROUTINE                    ; free space located by sdd1sites.py scanning
                                ;   for filler outside the compressed streams;
                                ;   the address differs per region, so the
                                ;   including file supplies it
sdd1_ch0:
    %translate($00)
sdd1_ch1:
    %translate($10)
sdd1_ch7:
    %translate($70)


; ---------------------------------------------------------------------------
; sdd1_chy
;
; The variant for $00:F7BF, the engine's table-driven DMA helper. There the
; channel is not fixed: the caller's parameter block supplies it, and by the
; time the arming store is reached Y holds the channel's register offset,
; already multiplied by 16. Everything above can hardcode the offset; this one
; has to carry it through the scan, which needs Y for its own cursor. The
; offset therefore lives on the stack and comes back with stack-relative
; addressing.
;
; Entry:  as the macro above, plus Y = channel register offset ($00, $10, ...).
; Exit:   as the macro above. Y is restored, so the caller's offset survives.
; ---------------------------------------------------------------------------
sdd1_chy:
    php
    phb
    rep #$30
    pha
    phx
    phy                         ; caller's Y, restored at the end
    tyx                         ; X = channel register offset

    pea $0000
    plb
    plb                         ; DBR = $00 so "$4302,x" reaches the registers
    lda $4302,x                 ; 16-bit source address
    phx                         ; park the channel offset; X is needed as the
                                ;   table index once the slot is known
    tay                         ; Y = scan cursor
    sep #$20
    lda $4304,x                 ; A = source bank

    pea $6060
    plb
    plb                         ; DBR = $60, the key table
.scan:
    cmp $0000,y
    beq .found
    iny
    bra .scan

.found:
    tyx                         ; X = slot
    lda.l !TABLE_LOW,x          ; stash the destination on the stack, because X
    pha                         ;   is about to go back to being the channel
    lda.l !TABLE_HIGH,x         ;   offset
    pha
    lda.l !TABLE_BANK,x
    pha
                                ; stack now, from the top: bank, high, low,
                                ; then the two bytes of the channel offset
    rep #$20
    lda $04,s                   ; recover the channel offset past those three
    tax
    sep #$20

    pea $0000
    plb
    plb                         ; DBR = $00 again for the register writes
    pla
    sta $4304,x                 ; bank
    pla
    sta $4303,x                 ; high
    pla
    sta $4302,x                 ; low

    lda $4300,x                 ; clear the fixed-address bit, as above
    and #$F7
    sta $4300,x

    rep #$30
    plx                         ; drop the parked channel offset
    ply
    plx
    pla
    plb
    plp
    rtl


